In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import PIL
from sklearn.cluster import KMeans
%matplotlib inline

In [10]:
## using K-means Clustering, pull a palette of size N of the most prominent colors of an image.
## outputs the palette for use in other projects
## converts the palette to a list of colors of form (R,G,B)
def strip_palette(image, size):
    #Open the image using openCV and convert to RGB
    img = cv.imread(image)
    img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
    
    #Little hazy at this point forward but create clusters on my image reshaped to be a vector whose entries are RBG colors
    clt = KMeans(n_clusters = size)
    clt.fit(img.reshape(-1,3))
    palette = []
    for color in clt.cluster_centers_:
        R, G, B = int(color[0]), int(color[1]), int(color[2])
        palette.append((R,G,B))
    return palette

In [11]:
palette = strip_palette("jess.jpg", 4)
palette

[(176, 138, 121), (224, 200, 166), (61, 47, 49), (112, 86, 84)]

In [8]:
for n in palette:
    print(n)

[224.07202908 200.36553041 167.00172825]
[61.73916101 47.94286069 49.39858961]
[177.41522242 138.63310336 121.36914694]
[113.04686816  86.75597893  84.65598428]
